server:
  port: ${SERVER_PORT:52001}

spring:
  sql:
    init:
      mode: never

# 개발 환경에서는 logback-spring.xml의 dev 프로필이 적용됩니다.
# 로깅 레벨 설정:
# - root: INFO
# - com.gijun.backend: DEBUG
# - io.r2dbc: DEBUG
# - org.springframework.r2dbc: DEBUG
