server:
  port: ${SERVER_PORT:52001}

spring:
  application:
    name: delivery-simulator
  
  # R2DBC MySQL 설정
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://localhost:3306/delivery}
    username: ${DB_USERNAME:dbuser}
    password: ${DB_PASSWORD:dbpass}
    properties:
      ssl: false
      sslMode: DISABLED
      connectionTimeZone: SERVER
      serverZoneId: "+09:00"
      useServerPrepareStatement: true
  
  # Redis 설정  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:}
      repositories:
        enabled: false
  
  # Kafka 설정
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: delivery-simulator
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
  
  # Jackson 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# 로깅 설정은 logback-spring.xml 파일에서 관리됩니다.
logging:
  config: classpath:logback-spring.xml
