server:
  port: ${SERVER_PORT:52001}

spring:
  application:
    name: delivery-simulator
  
  # R2DBC MySQL 설정 - 필수가 아닌 경우 비활성화 가능
  r2dbc:
    url: ${DB_URL:r2dbc:mysql://210.121.177.150:3306/delivery?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:gijunpark}
    password: ${DB_PASSWORD:park9832}
    properties:
      ssl: false
      sslMode: DISABLED
      connectionTimeZone: SERVER
      serverZoneId: "+09:00"
      useServerPrepareStatement: true
  
  # 스키마 초기화 설정
  sql:
    init:
      mode: always                            # 항상 초기화(embedded, always, never)
      schema-locations: classpath:schema.sql  # 스키마 생성 SQL 위치
      data-locations: classpath:data.sql      # 초기 데이터 SQL 위치
      separator: ;                            # SQL 문 구분자
      encoding: UTF-8                         # 인코딩
      continue-on-error: false                # 오류 발생 시 계속 진행 여부

  # Redis 설정 - 필수가 아닌 경우 비활성화 가능
  data:
    redis:
      enabled: ${REDIS_ENABLED:true}
      host: ${REDIS_HOST:210.121.177.150}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:park983200}
      repositories:
        enabled: false
  
  # Kafka 설정 - 필수가 아닌 경우 비활성화 가능
  kafka:
    enabled: ${KAFKA_ENABLED:true}
    bootstrap-servers: ${KAFKA_SERVERS:210.121.177.150:9092}
    consumer:
      group-id: delivery-simulator
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
  
  # Jackson 설정
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

# 로깅 설정은 logback-spring.xml 파일에서 관리됩니다.
logging:
  config: classpath:logback-spring.xml